### ISSUE TITLE
"Activity log for all visible items" returning non visible items (?)

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#843] opened 2022-04-27 09:14 UTC
## Motivations
When calling (token of the usual user):
```
curl 'https://dev.algorea.org/api/items/log?limit=20&watched_group_id=49268055312628123' -H 'Authorization: Bearer ***''
```
... I get the title "Locked content" of item 6577229663440413612 which is not supposed to be visible to the current-user (at least `https://dev.algorea.org/api/items/6577229663440413612/path-from-root` returns a 403)

## Subtasks
* Fix the service: activities of non-visible items should not be returned

**Comment by zenovich** [comment] 2022-09-20 22:48
Cannot reproduce:
```https://dev.algorea.org/api/items/6577229663440413612/path-from-root``` still returns 403, but there is no 6577229663440413612 item in output of ```https://dev.algorea.org/api/items/log?limit=20&watched_group_id=49268055312628123```

**Comment by smadbe** [comment] 2023-01-06 16:36
It is because there have been a long time between the creation of the issue and your request. If you increase the limit to 100, you'll get it.

**Comment by smadbe** [comment] 2023-01-06 16:38
Of course, it is worth checking it is not related to the problem in path-from-root mentioned in #850

**Comment by GeoffreyHuck** [comment] 2023-06-20 03:58
New status: Blocked

Waiting for https://github.com/France-ioi/AlgoreaBackend/pull/961 to be merged and deployed, and the issue to be tested again to make sure it didn't fix it.

**Comment by smadbe** [comment] 2023-09-15 08:23
Should not be blocked anymore.

**Comment by GeoffreyHuck** [comment] 2023-09-18 07:09
Just checked `https://dev.algorea.org/api/items/6577229663440413612/path-from-root`: the path is now returned, it works!

**Closed** 2023-09-18 14:27 UTC
Labels: Type: Bug
